export const FETCH_BRANCH = "fetchBranch"
export const DELETE_BRANCH = "deleteBranch"
export const UPDATE_BRANCH = "updateBranch"
export const SHOW_BRANCH = "showBranch"
export const CREATE_BRANCH = "createBranch"
